In [21]:
import torch
import torch.nn as nn

In [17]:
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X = torch.tensor([[10, 20, 30],[40,50,60]])
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1

In [18]:
print(X.shape)

torch.Size([2, 3])


In [19]:
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [13]:
print(X)

tensor([[[10],
         [20],
         [30]],

        [[40],
         [50],
         [60]]])


In [76]:
rnn = nn.RNN(1, 1, 1) #input_size, hidden_size, num_layers=1,
#input_size->no. of expected features in input x.

In [77]:
input = torch.randn(3, 1)# n, sequence_length, input_size

In [78]:
print(input.shape)#
print(input)

torch.Size([3, 1])
tensor([[-1.9990],
        [-0.8887],
        [-0.5633]])


In [81]:
h0 = torch.randn(1, 1) #n, num_layers, hidden_size
print(h0.shape)

torch.Size([1, 1])


In [82]:
output, hn = rnn(input, h0)# output = sequence_length, hidden_size

In [83]:
print(output)
print(output.shape)

tensor([[-0.9796],
        [-0.9851],
        [-0.9814]], grad_fn=<SqueezeBackward1>)
torch.Size([3, 1])


In [84]:
print(hn.shape)

torch.Size([1, 1])


In [93]:
 print(rnn.all_weights)

[[Parameter containing:
tensor([[0.3609]], requires_grad=True), Parameter containing:
tensor([[0.9938]], requires_grad=True), Parameter containing:
tensor([-0.4162], requires_grad=True), Parameter containing:
tensor([-0.7360], requires_grad=True)]]


In [87]:
print(rnn.parameters())

<generator object Module.parameters at 0x7fe1a9736190>
